use crate::SyntaxKind;

/// Canonical keyword table for IEEE 1800-2023.
///
/// Sorted by string for binary search. This is the single source of truth --
/// `classify_keyword` derives its behavior from this table.
///
/// The LRM (22.14) defines `begin_keywords`/`end_keywords` directives that
/// restrict the active keyword set by version (e.g. `"1364-2001"` only
/// reserves Verilog-2001 keywords). This lexer does not yet support version
/// gating -- all 1800-2023 keywords are always reserved. When version gating
/// is added, filter from this same table.
pub(crate) static KEYWORDS: &[(&str, SyntaxKind)] = &[
    ("accept_on", SyntaxKind::AcceptOnKw),
    ("alias", SyntaxKind::AliasKw),
    ("always", SyntaxKind::AlwaysKw),
    ("always_comb", SyntaxKind::AlwaysCombKw),
    ("always_ff", SyntaxKind::AlwaysFfKw),
    ("always_latch", SyntaxKind::AlwaysLatchKw),
    ("and", SyntaxKind::AndKw),
    ("assert", SyntaxKind::AssertKw),
    ("assign", SyntaxKind::AssignKw),
    ("assume", SyntaxKind::AssumeKw),
    ("automatic", SyntaxKind::AutomaticKw),
    ("before", SyntaxKind::BeforeKw),
    ("begin", SyntaxKind::BeginKw),
    ("bind", SyntaxKind::BindKw),
    ("bins", SyntaxKind::BinsKw),
    ("binsof", SyntaxKind::BinsofKw),
    ("bit", SyntaxKind::BitKw),
    ("break", SyntaxKind::BreakKw),
    ("buf", SyntaxKind::BufKw),
    ("bufif0", SyntaxKind::Bufif0Kw),
    ("bufif1", SyntaxKind::Bufif1Kw),
    ("byte", SyntaxKind::ByteKw),
    ("case", SyntaxKind::CaseKw),
    ("casex", SyntaxKind::CasexKw),
    ("casez", SyntaxKind::CasezKw),
    ("cell", SyntaxKind::CellKw),
    ("chandle", SyntaxKind::ChandleKw),
    ("checker", SyntaxKind::CheckerKw),
    ("class", SyntaxKind::ClassKw),
    ("clocking", SyntaxKind::ClockingKw),
    ("cmos", SyntaxKind::CmosKw),
    ("config", SyntaxKind::ConfigKw),
    ("const", SyntaxKind::ConstKw),
    ("constraint", SyntaxKind::ConstraintKw),
    ("context", SyntaxKind::ContextKw),
    ("continue", SyntaxKind::ContinueKw),
    ("cover", SyntaxKind::CoverKw),
    ("covergroup", SyntaxKind::CovergroupKw),
    ("coverpoint", SyntaxKind::CoverpointKw),
    ("cross", SyntaxKind::CrossKw),
    ("deassign", SyntaxKind::DeassignKw),
    ("default", SyntaxKind::DefaultKw),
    ("defparam", SyntaxKind::DefparamKw),
    ("design", SyntaxKind::DesignKw),
    ("disable", SyntaxKind::DisableKw),
    ("dist", SyntaxKind::DistKw),
    ("do", SyntaxKind::DoKw),
    ("edge", SyntaxKind::EdgeKw),
    ("else", SyntaxKind::ElseKw),
    ("end", SyntaxKind::EndKw),
    ("endcase", SyntaxKind::EndcaseKw),
    ("endchecker", SyntaxKind::EndcheckerKw),
    ("endclass", SyntaxKind::EndclassKw),
    ("endclocking", SyntaxKind::EndclockingKw),
    ("endconfig", SyntaxKind::EndconfigKw),
    ("endfunction", SyntaxKind::EndfunctionKw),
    ("endgenerate", SyntaxKind::EndgenerateKw),
    ("endgroup", SyntaxKind::EndgroupKw),
    ("endinterface", SyntaxKind::EndinterfaceKw),
    ("endmodule", SyntaxKind::EndmoduleKw),
    ("endpackage", SyntaxKind::EndpackageKw),
    ("endprimitive", SyntaxKind::EndprimitiveKw),
    ("endprogram", SyntaxKind::EndprogramKw),
    ("endproperty", SyntaxKind::EndpropertyKw),
    ("endsequence", SyntaxKind::EndsequenceKw),
    ("endspecify", SyntaxKind::EndspecifyKw),
    ("endtable", SyntaxKind::EndtableKw),
    ("endtask", SyntaxKind::EndtaskKw),
    ("enum", SyntaxKind::EnumKw),
    ("event", SyntaxKind::EventKw),
    ("eventually", SyntaxKind::EventuallyKw),
    ("expect", SyntaxKind::ExpectKw),
    ("export", SyntaxKind::ExportKw),
    ("extends", SyntaxKind::ExtendsKw),
    ("extern", SyntaxKind::ExternKw),
    ("final", SyntaxKind::FinalKw),
    ("first_match", SyntaxKind::FirstMatchKw),
    ("for", SyntaxKind::ForKw),
    ("force", SyntaxKind::ForceKw),
    ("foreach", SyntaxKind::ForeachKw),
    ("forever", SyntaxKind::ForeverKw),
    ("fork", SyntaxKind::ForkKw),
    ("forkjoin", SyntaxKind::ForkjoinKw),
    ("function", SyntaxKind::FunctionKw),
    ("generate", SyntaxKind::GenerateKw),
    ("genvar", SyntaxKind::GenvarKw),
    ("global", SyntaxKind::GlobalKw),
    ("highz0", SyntaxKind::Highz0Kw),
    ("highz1", SyntaxKind::Highz1Kw),
    ("if", SyntaxKind::IfKw),
    ("iff", SyntaxKind::IffKw),
    ("ifnone", SyntaxKind::IfnoneKw),
    ("ignore_bins", SyntaxKind::IgnoreBinsKw),
    ("illegal_bins", SyntaxKind::IllegalBinsKw),
    ("implements", SyntaxKind::ImplementsKw),
    ("implies", SyntaxKind::ImpliesKw),
    ("import", SyntaxKind::ImportKw),
    ("incdir", SyntaxKind::IncdirKw),
    ("include", SyntaxKind::IncludeKw),
    ("initial", SyntaxKind::InitialKw),
    ("inout", SyntaxKind::InoutKw),
    ("input", SyntaxKind::InputKw),
    ("inside", SyntaxKind::InsideKw),
    ("instance", SyntaxKind::InstanceKw),
    ("int", SyntaxKind::IntKw),
    ("integer", SyntaxKind::IntegerKw),
    ("interconnect", SyntaxKind::InterconnectKw),
    ("interface", SyntaxKind::InterfaceKw),
    ("intersect", SyntaxKind::IntersectKw),
    ("join", SyntaxKind::JoinKw),
    ("join_any", SyntaxKind::JoinAnyKw),
    ("join_none", SyntaxKind::JoinNoneKw),
    ("large", SyntaxKind::LargeKw),
    ("let", SyntaxKind::LetKw),
    ("liblist", SyntaxKind::LiblistKw),
    ("library", SyntaxKind::LibraryKw),
    ("local", SyntaxKind::LocalKw),
    ("localparam", SyntaxKind::LocalparamKw),
    ("logic", SyntaxKind::LogicKw),
    ("longint", SyntaxKind::LongintKw),
    ("macromodule", SyntaxKind::MacromoduleKw),
    ("matches", SyntaxKind::MatchesKw),
    ("medium", SyntaxKind::MediumKw),
    ("modport", SyntaxKind::ModportKw),
    ("module", SyntaxKind::ModuleKw),
    ("nand", SyntaxKind::NandKw),
    ("negedge", SyntaxKind::NegedgeKw),
    ("nettype", SyntaxKind::NettypeKw),
    ("new", SyntaxKind::NewKw),
    ("nexttime", SyntaxKind::NexttimeKw),
    ("nmos", SyntaxKind::NmosKw),
    ("nor", SyntaxKind::NorKw),
    ("noshowcancelled", SyntaxKind::NoshowcancelledKw),
    ("not", SyntaxKind::NotKw),
    ("notif0", SyntaxKind::Notif0Kw),
    ("notif1", SyntaxKind::Notif1Kw),
    ("null", SyntaxKind::NullKw),
    ("or", SyntaxKind::OrKw),
    ("output", SyntaxKind::OutputKw),
    ("package", SyntaxKind::PackageKw),
    ("packed", SyntaxKind::PackedKw),
    ("parameter", SyntaxKind::ParameterKw),
    ("pmos", SyntaxKind::PmosKw),
    ("posedge", SyntaxKind::PosedgeKw),
    ("primitive", SyntaxKind::PrimitiveKw),
    ("priority", SyntaxKind::PriorityKw),
    ("program", SyntaxKind::ProgramKw),
    ("property", SyntaxKind::PropertyKw),
    ("protected", SyntaxKind::ProtectedKw),
    ("pull0", SyntaxKind::Pull0Kw),
    ("pull1", SyntaxKind::Pull1Kw),
    ("pulldown", SyntaxKind::PulldownKw),
    ("pullup", SyntaxKind::PullupKw),
    ("pulsestyle_ondetect", SyntaxKind::PulsestyleOndetectKw),
    ("pulsestyle_onevent", SyntaxKind::PulsestyleOneventKw),
    ("pure", SyntaxKind::PureKw),
    ("rand", SyntaxKind::RandKw),
    ("randc", SyntaxKind::RandcKw),
    ("randcase", SyntaxKind::RandcaseKw),
    ("randsequence", SyntaxKind::RandsequenceKw),
    ("rcmos", SyntaxKind::RcmosKw),
    ("real", SyntaxKind::RealKw),
    ("realtime", SyntaxKind::RealtimeKw),
    ("ref", SyntaxKind::RefKw),
    ("reg", SyntaxKind::RegKw),
    ("reject_on", SyntaxKind::RejectOnKw),
    ("release", SyntaxKind::ReleaseKw),
    ("repeat", SyntaxKind::RepeatKw),
    ("restrict", SyntaxKind::RestrictKw),
    ("return", SyntaxKind::ReturnKw),
    ("rnmos", SyntaxKind::RnmosKw),
    ("rpmos", SyntaxKind::RpmosKw),
    ("rtran", SyntaxKind::RtranKw),
    ("rtranif0", SyntaxKind::Rtranif0Kw),
    ("rtranif1", SyntaxKind::Rtranif1Kw),
    ("s_always", SyntaxKind::SAlwaysKw),
    ("s_eventually", SyntaxKind::SEventuallyKw),
    ("s_nexttime", SyntaxKind::SNexttimeKw),
    ("s_until", SyntaxKind::SUntilKw),
    ("s_until_with", SyntaxKind::SUntilWithKw),
    ("scalared", SyntaxKind::ScalaredKw),
    ("sequence", SyntaxKind::SequenceKw),
    ("shortint", SyntaxKind::ShortintKw),
    ("shortreal", SyntaxKind::ShortRealKw),
    ("showcancelled", SyntaxKind::ShowcancelledKw),
    ("signed", SyntaxKind::SignedKw),
    ("small", SyntaxKind::SmallKw),
    ("soft", SyntaxKind::SoftKw),
    ("solve", SyntaxKind::SolveKw),
    ("specify", SyntaxKind::SpecifyKw),
    ("specparam", SyntaxKind::SpecparamKw),
    ("static", SyntaxKind::StaticKw),
    ("string", SyntaxKind::StringKw),
    ("strong", SyntaxKind::StrongKw),
    ("strong0", SyntaxKind::Strong0Kw),
    ("strong1", SyntaxKind::Strong1Kw),
    ("struct", SyntaxKind::StructKw),
    ("super", SyntaxKind::SuperKw),
    ("supply0", SyntaxKind::Supply0Kw),
    ("supply1", SyntaxKind::Supply1Kw),
    ("sync_accept_on", SyntaxKind::SyncAcceptOnKw),
    ("sync_reject_on", SyntaxKind::SyncRejectOnKw),
    ("table", SyntaxKind::TableKw),
    ("tagged", SyntaxKind::TaggedKw),
    ("task", SyntaxKind::TaskKw),
    ("this", SyntaxKind::ThisKw),
    ("throughout", SyntaxKind::ThroughoutKw),
    ("time", SyntaxKind::TimeKw),
    ("timeprecision", SyntaxKind::TimeprecisionKw),
    ("timeunit", SyntaxKind::TimeunitKw),
    ("tran", SyntaxKind::TranKw),
    ("tranif0", SyntaxKind::Tranif0Kw),
    ("tranif1", SyntaxKind::Tranif1Kw),
    ("tri", SyntaxKind::TriKw),
    ("tri0", SyntaxKind::Tri0Kw),
    ("tri1", SyntaxKind::Tri1Kw),
    ("triand", SyntaxKind::TriandKw),
    ("trior", SyntaxKind::TriorKw),
    ("trireg", SyntaxKind::TriregKw),
    ("type", SyntaxKind::TypeKw),
    ("typedef", SyntaxKind::TypedefKw),
    ("union", SyntaxKind::UnionKw),
    ("unique", SyntaxKind::UniqueKw),
    ("unique0", SyntaxKind::Unique0Kw),
    ("unsigned", SyntaxKind::UnsignedKw),
    ("until", SyntaxKind::UntilKw),
    ("until_with", SyntaxKind::UntilWithKw),
    ("untyped", SyntaxKind::UntypedKw),
    ("use", SyntaxKind::UseKw),
    ("uwire", SyntaxKind::UwireKw),
    ("var", SyntaxKind::VarKw),
    ("vectored", SyntaxKind::VectoredKw),
    ("virtual", SyntaxKind::VirtualKw),
    ("void", SyntaxKind::VoidKw),
    ("wait", SyntaxKind::WaitKw),
    ("wait_order", SyntaxKind::WaitOrderKw),
    ("wand", SyntaxKind::WandKw),
    ("weak", SyntaxKind::WeakKw),
    ("weak0", SyntaxKind::Weak0Kw),
    ("weak1", SyntaxKind::Weak1Kw),
    ("while", SyntaxKind::WhileKw),
    ("wildcard", SyntaxKind::WildcardKw),
    ("wire", SyntaxKind::WireKw),
    ("with", SyntaxKind::WithKw),
    ("within", SyntaxKind::WithinKw),
    ("wor", SyntaxKind::WorKw),
    ("xnor", SyntaxKind::XnorKw),
    ("xor", SyntaxKind::XorKw),
];

/// Classify an identifier string as a keyword or plain `Ident`.
///
/// Uses binary search on the canonical `KEYWORDS` table.
pub(crate) fn classify_keyword(word: &str) -> SyntaxKind {
    match KEYWORDS.binary_search_by_key(&word, |(k, _)| k) {
        Ok(i) => KEYWORDS[i].1,
        Err(_) => SyntaxKind::Ident,
    }
}

#[cfg(test)]
mod tests {
    use super::{KEYWORDS, classify_keyword};

    #[test]
    fn table_is_sorted_and_unique() {
        for window in KEYWORDS.windows(2) {
            let (a, _) = window[0];
            let (b, _) = window[1];
            assert!(a < b, "KEYWORDS table not sorted: {a:?} >= {b:?}");
        }
    }

    #[test]
    fn every_entry_round_trips() {
        for &(word, expected) in KEYWORDS {
            assert_eq!(
                classify_keyword(word),
                expected,
                "classify_keyword({word:?}) returned wrong kind"
            );
        }
    }
}
