/// Token kinds for `SystemVerilog`.
///
/// Layout: tokens `0..NODE_START`, nodes `NODE_START..`.
///
/// Stability rules:
/// - **Never reorder or remove existing variants.**
/// - **Append new tokens before `__NodeStart`; append new nodes after it.**
/// - Token ordinals are stable across releases. Adding new tokens shifts
///   `__NodeStart` and node ordinals, which is expected -- node ordinals are
///   workspace-internal (never serialized) and recompiled together.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum SyntaxKind {
    // Trivia
    Whitespace = 0,
    LineComment,
    BlockComment,

    // Punctuation (original)
    Semicolon,
    Comma,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Colon,
    Dot,
    Assign,
    At,
    Hash,

    // Operators (original)
    Plus,
    Minus,
    Star,
    Slash,

    // Literals (original)
    IntLiteral,
    StringLiteral,

    // Identifiers (original)
    Ident,

    // Keywords (original 16)
    ModuleKw,
    EndmoduleKw,
    InputKw,
    OutputKw,
    InoutKw,
    WireKw,
    RegKw,
    LogicKw,
    AssignKw,
    AlwaysKw,
    InitialKw,
    BeginKw,
    EndKw,
    IfKw,
    ElseKw,
    ParameterKw,

    // Special
    Error,
    Eof,

    // Operators and punctuation (new)
    Bang,
    Tilde,
    Percent,
    Amp,
    Pipe,
    Caret,
    Question,
    EqEq,
    BangEq,
    EqEqEq,
    BangEqEq,
    EqEqQuestion,
    BangEqQuestion,
    AmpAmp,
    PipePipe,
    StarStar,
    Lt,
    LtEq,
    Gt,
    GtEq,
    LtLt,
    GtGt,
    LtLtLt,
    GtGtGt,
    TildeAmp,
    TildePipe,
    TildeCaret,
    CaretTilde,
    PlusPlus,
    MinusMinus,
    MinusGt,
    MinusGtGt,
    LtMinusGt,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    AmpEq,
    PipeEq,
    CaretEq,
    LtLtEq,
    GtGtEq,
    LtLtLtEq,
    GtGtGtEq,
    HashHash,
    ColonColon,
    ColonEq,
    ColonSlash,
    TickBrace,
    DotStar,

    // Literal tokens (new)
    BasedLiteral,
    RealLiteral,
    UnbasedUnsizedLiteral,
    TimeLiteral,

    // Identifier tokens (new)
    SystemIdent,
    EscapedIdent,
    Directive,

    // Keywords (new, alphabetical)
    AcceptOnKw,
    AliasKw,
    AlwaysCombKw,
    AlwaysFfKw,
    AlwaysLatchKw,
    AndKw,
    AssertKw,
    AssumeKw,
    AutomaticKw,
    BeforeKw,
    BindKw,
    BinsKw,
    BinsofKw,
    BitKw,
    BreakKw,
    BufKw,
    Bufif0Kw,
    Bufif1Kw,
    ByteKw,
    CaseKw,
    CasexKw,
    CasezKw,
    CellKw,
    ChandleKw,
    CheckerKw,
    ClassKw,
    ClockingKw,
    CmosKw,
    ConfigKw,
    ConstKw,
    ConstraintKw,
    ContextKw,
    ContinueKw,
    CoverKw,
    CovergroupKw,
    CoverpointKw,
    CrossKw,
    DeassignKw,
    DefaultKw,
    DefparamKw,
    DesignKw,
    DisableKw,
    DistKw,
    DoKw,
    EdgeKw,
    EndcaseKw,
    EndcheckerKw,
    EndclassKw,
    EndclockingKw,
    EndconfigKw,
    EndfunctionKw,
    EndgenerateKw,
    EndgroupKw,
    EndinterfaceKw,
    EndpackageKw,
    EndprimitiveKw,
    EndprogramKw,
    EndpropertyKw,
    EndspecifyKw,
    EndsequenceKw,
    EndtableKw,
    EndtaskKw,
    EnumKw,
    EventKw,
    EventuallyKw,
    ExpectKw,
    ExportKw,
    ExtendsKw,
    ExternKw,
    FinalKw,
    FirstMatchKw,
    ForKw,
    ForceKw,
    ForeachKw,
    ForeverKw,
    ForkKw,
    ForkjoinKw,
    FunctionKw,
    GenerateKw,
    GenvarKw,
    GlobalKw,
    Highz0Kw,
    Highz1Kw,
    IffKw,
    IfnoneKw,
    IgnoreBinsKw,
    IllegalBinsKw,
    ImplementsKw,
    ImpliesKw,
    ImportKw,
    IncdirKw,
    IncludeKw,
    InsideKw,
    InstanceKw,
    IntKw,
    IntegerKw,
    InterconnectKw,
    InterfaceKw,
    IntersectKw,
    JoinKw,
    JoinAnyKw,
    JoinNoneKw,
    LargeKw,
    LetKw,
    LiblistKw,
    LibraryKw,
    LocalKw,
    LocalparamKw,
    LongintKw,
    MacromoduleKw,
    MatchesKw,
    MediumKw,
    ModportKw,
    NandKw,
    NegedgeKw,
    NettypeKw,
    NewKw,
    NexttimeKw,
    NmosKw,
    NorKw,
    NoshowcancelledKw,
    NotKw,
    Notif0Kw,
    Notif1Kw,
    NullKw,
    OrKw,
    PackageKw,
    PackedKw,
    PmosKw,
    PosedgeKw,
    PrimitiveKw,
    PriorityKw,
    ProgramKw,
    PropertyKw,
    ProtectedKw,
    Pull0Kw,
    Pull1Kw,
    PulldownKw,
    PullupKw,
    PulsestyleOndetectKw,
    PulsestyleOneventKw,
    PureKw,
    RandKw,
    RandcKw,
    RandcaseKw,
    RandsequenceKw,
    RcmosKw,
    RealKw,
    RealtimeKw,
    RefKw,
    RejectOnKw,
    ReleaseKw,
    RepeatKw,
    RestrictKw,
    ReturnKw,
    RnmosKw,
    RpmosKw,
    RtranKw,
    Rtranif0Kw,
    Rtranif1Kw,
    SAlwaysKw,
    SEventuallyKw,
    SNexttimeKw,
    SUntilKw,
    SUntilWithKw,
    ScalaredKw,
    SequenceKw,
    ShortintKw,
    ShortRealKw,
    ShowcancelledKw,
    SignedKw,
    SmallKw,
    SoftKw,
    SolveKw,
    SpecifyKw,
    SpecparamKw,
    StaticKw,
    StringKw,
    StrongKw,
    Strong0Kw,
    Strong1Kw,
    StructKw,
    SuperKw,
    Supply0Kw,
    Supply1Kw,
    SyncAcceptOnKw,
    SyncRejectOnKw,
    TableKw,
    TaggedKw,
    TaskKw,
    ThisKw,
    ThroughoutKw,
    TimeKw,
    TimeprecisionKw,
    TimeunitKw,
    TranKw,
    Tranif0Kw,
    Tranif1Kw,
    TriKw,
    Tri0Kw,
    Tri1Kw,
    TriandKw,
    TriorKw,
    TriregKw,
    TypeKw,
    TypedefKw,
    UnionKw,
    UniqueKw,
    Unique0Kw,
    UnsignedKw,
    UntilKw,
    UntilWithKw,
    UntypedKw,
    UseKw,
    UwireKw,
    VarKw,
    VectoredKw,
    VirtualKw,
    VoidKw,
    WaitKw,
    WaitOrderKw,
    WandKw,
    WeakKw,
    Weak0Kw,
    Weak1Kw,
    WhileKw,
    WildcardKw,
    WithKw,
    WithinKw,
    WorKw,
    XnorKw,
    XorKw,

    // Attribute delimiters
    AttrOpen,
    AttrClose,

    // Bare tick (cast expression prefix)
    Tick,

    // Node boundary
    #[doc(hidden)]
    __NodeStart,

    // Nodes (used by parser/rowan)
    SourceFile,
    ModuleDecl,
    PortList,
    Port,
    ModuleBody,
    ContinuousAssign,
    Expression,
    ParamDecl,
    ParamPortList,
    AlwaysBlock,
    InitialBlock,
    ModuleInstantiation,
    InstancePortList,
    InstancePort,
    NetDecl,
    VarDecl,
    TypeSpec,
    PackedDimension,
    UnpackedDimension,
    BlockStmt,
    IfStmt,
    CaseStmt,
    CaseItem,
    ForStmt,
    WhileStmt,
    RepeatStmt,
    ForeverStmt,
    AssignStmt,
    TimingControl,
    EventExpr,
    EventItem,
    BinExpr,
    PrefixExpr,
    ParenExpr,
    CondExpr,
    ConcatExpr,
    ReplicExpr,
    IndexExpr,
    RangeExpr,
    FieldExpr,
    CallExpr,
    ArgList,
    NameRef,
    Literal,
    ErrorNode,
    Declarator,
    PackageDecl,
    PackageBody,
    ImportDecl,
    ImportItem,
    QualifiedName,
    TypedefDecl,
    InterfaceDecl,
    InterfaceBody,
    ProgramDecl,
    ProgramBody,
    PrimitiveDecl,
    ConfigDecl,
    EnumType,
    EnumMember,
    StructType,
    StructMember,
    SystemTfCall,
    SystemTfArgList,
    GenerateRegion,
    GenvarDecl,
    AttrInst,
    AttrSpec,
    FunctionDecl,
    TaskDecl,
    TfPortDecl,
    AssignmentPatternItem,
    NewExpr,
    ExportDecl,
    ExportItem,
    ModportDecl,
    ModportItem,
    ModportPort,
    ModportExprPort,
    DottedName,
    // Streaming operators (LRM 11.4.14)
    StreamExpr,
    StreamSliceSize,
    StreamOperands,

    // Standalone dollar (queue/assoc dim delimiter)
    Dollar,

    // Enum member range (LRM 6.19.3)
    EnumMemberRange,

    // Cast expression (LRM 6.24)
    CastExpr,

    // Streaming `with` clause (LRM 11.4.14.4)
    StreamOperandItem,
    StreamWithClause,
    StreamRange,

    // Per-instance wrapper in module instantiation (LRM 23.3.2)
    HierarchicalInstance,

    #[doc(hidden)]
    __Last,
}

impl SyntaxKind {
    /// Whether this kind is trivia (whitespace or comments).
    pub fn is_trivia(self) -> bool {
        matches!(
            self,
            Self::Whitespace | Self::LineComment | Self::BlockComment
        )
    }
}

/// First node kind value -- tokens are `< NODE_START`, nodes `>= NODE_START`.
pub const NODE_START: u16 = SyntaxKind::__NodeStart as u16;
